### ISSUE TITLE
ok fails with python2

### ISSUE THREAD

**Issue by svenssonaxel** [secretGeek/ok-bash#20]
It seems that ok fails on systems where python3 is not available. This is on CentOS 7 with python 2.7.5 and ok-bash trunk as of today (1ebd407):

```
$ python --version
Python 2.7.5
$ ok --version
ok-bash 0.8.0
$ ok
Traceback (most recent call last):
  File "/home/sweaxsadm/ok-bash/ok-show.py", line 186, in <module>
    main()
  File "/home/sweaxsadm/ok-bash/ok-show.py", line 133, in main
    terminal_size = shutil.get_terminal_size()
AttributeError: 'module' object has no attribute 'get_terminal_size'
```

**Comment by svenssonaxel** [comment]
The problem was introduced in 25528cd97566b7584efa0631483f1d91f2181642

**Comment by doekman** [comment]
Thanks for the report. A fix is coming up. You could test it in branch [new-year-resolution](https://github.com/secretGeek/ok-bash/tree/new-year-resolution). I hope to merge this shortly, but no promises.

**Comment by svenssonaxel** [comment]
Tested and confirmed:
Fixed in 1c2c5bd and works on the `new-year-resolution` branch.

Thank you!
